services:

  db:
    image: timescale/timescaledb:latest-pg17
    environment:
      - PGDATA=/pgdata
      - POSTGRES_USER=iot
      - POSTGRES_PASSWORD=sensor
      - POSTGRES_DB=sensor_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/pgdata
    networks:
      - sha_network

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - sha_network

  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - sha_network

  collector:
    build:
      context: .
      dockerfile: collector/Dockerfile
    environment:
      - SHM_MQTT_HOST=mqtt_broker
      - SHM_MQTT_PORT=1883
      - RUST_LOG=debug
    depends_on:
      - mqtt_broker
    networks:
      - sha_network

volumes:
  pg_data:
  grafana_storage:

networks:
  sha_network:
