services:

  nats:
    image: nats:latest
    command: ["-js", "-sd", "/data", "-DV"]
    volumes:
      - nats_data:/data
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - iot_network

  db:
    image: timescale/timescaledb:latest-pg17
    environment:
      - PGDATA=/pgdata
      - POSTGRES_USER=iot
      - POSTGRES_PASSWORD=sensor
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/pgdata

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana

  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - iot_network

volumes:
  nats_data:
  pg_data:
  grafana_storage:

networks:
  iot_network:
    driver: bridge
