services:

  nats:
    image: nats:latest
    command: ["-js", "-sd", "/data", "-DV"]
    volumes:
      - nats_data:/data
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - iot_network

  db:
    image: timescale/timescaledb:latest-pg17
    environment:
      - PGDATA=/pgdata
      - POSTGRES_USER=iot
      - POSTGRES_PASSWORD=sensor
      - POSTGRES_DB=sensor_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/pgdata
    networks:
      - iot_network

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana/grafana.db
    networks:
      - iot_network

  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - iot_network

  mqtt_worker:
    build:
      context: .
      dockerfile: mqtt_worker/Dockerfile
    environment:
      - IOT_NATS_URL=nats://nats:4222
      - IOT_MQTT_HOST=mqtt_broker
      - IOT_MQTT_PORT=1883
      - RUST_LOG=debug
    depends_on:
      - mqtt_broker
      - nats
    networks:
      - iot_network

  dispatcher:
    build:
      context: .
      dockerfile: dispatcher/Dockerfile
    environment:
      - IOT_NATS_URL=nats://nats:4222
      - IOT_DATABASE_URL=postgres://iot:sensor@db/sensor_db
      - RUST_LOG=debug
    depends_on:
      - db
      - nats
    networks:
      - iot_network

volumes:
  nats_data:
  pg_data:
  grafana_storage:

networks:
  iot_network:
